An: <kaufmännischer Ansprechpartner>; <fachlicher Ansprechpartner>; <technischer Ansprechpartnere>
Betreff: Order: <Order-ID> Order-Bezeichnung: <Titel der Anfrage> (Kundenreferenz: [<Kundenreferenznummer>]) ist final abgeschlossen

Sehr geehrte Damen und Herren,
die von Ihnen beauftragte Order <Order-Nr.> „<Titel der Anfrage>“ (Kundenreferenz: <Kundenreferenznummer>) wurde bei FI-TS final abgeschlossen.
Bei Rückfragen können Sie sich an den verantwortlichen Ordermanager <Name Ordermanager> (E-Mail-Adresse Ordermanager) wenden.

Freundliche Grüße

FI-TS Ordermanagement

www.f-i-ts.de
FI-TS Sicherheitshinweis

Finanz Informatik Technologie Service GmbH & Co. KG
Handelsregister HRA 69637, Sitz: Haar, Amtsgericht München
Finanz Informatik Technologie Service Beteiligungsgesellschaft mbH
Handelsregister HRB 105291, Sitz: Haar, Amtsgericht München
Geschäftsführer: Christoph Röger (Vorsitzender), Andreas Kopp, Dr. Christian Thiel
Vorsitzender des Aufsichtsrates: Detlev Klage

